export const UPLOAD_FILE_FULFILLED = "UPLOAD_FILE_FULFILLED";
export const UPLOAD_FILE__REJECTED = "UPLOAD_FILE__REJECTED";

export const FILE_SAVED = "FILE_SAVED";
export const FILE_REJECTED = "FILE_REJECTED";
