version: "3"
services:
  db:
    container_name: database
    restart: always
    build: ./
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - nginx-proxy
networks:
  nginx-proxy:
volumes:
  pgdata:
