export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const REGISTER_FULFILLED = 'REGISTER_FULFILLED';
export const REGISTER_REJECTED = 'REGISTER_REJECTED';

export const REQUEST_RESET_PASSWORD_FULFILLED = 'REQUEST_RESET_PASSWORD_FULFILLED';
export const REQUEST_RESET_PASSWORD_REJECTED = 'REQUEST_RESET_PASSWORD_REJECTED';

export const UUID_FULFILLED = 'UUID_FULFILLED';
export const UUID_REJECTED = 'UUID_REJECTED';

export const RESET_PASSWORD_FULFILLED = 'RESET_PASSWORD_FULFILLED';
export const RESET_PASSWORD_REJECTED = 'RESET_PASSWORD_REJECTED';

export const VERIFY_VERIFICATION_FULFILLED = 'VERIFY_VERIFICATION_FULFILLED';
export const VERIFY_VERIFICATION_REJECTED = 'VERIFY_VERIFICATION_REJECTED';
