export const UPLOAD_FILE_FULFILLED = "UPLOAD_FILE_FULFILLED";
export const UPLOAD_FILE__REJECTED = "UPLOAD_FILE__REJECTED";

export const FILE_SAVED = "FILE_SAVED";
export const FILE_REJECTED = "FILE_REJECTED";

export const GET_SUB_LIST_FULFILLED = "GET_SUB_LIST_FULFILLED";
export const GET_SUB_LIST_REJECTED = "GET_SUB_LIST_REJECTED";


export const UPLOAD_IMAGES_TO_CLOUD_FULFILLED = "UPLOAD_IMAGES_TO_CLOUD_FULFILLED";
export const UPLOAD_IMAGES_TO_CLOUD_REJECTED = "UPLOAD_IMAGES_TO_CLOUD_REJECTED";
