export const INIT_SUBMISSION_FULFILLED = "INIT_SUBMISSION_FULFILLED";
export const INIT_SUBMISSION_REJECTED = "INIT_SUBMISSION_REJECTED";

export const SUBMISSIONS_LIST_FULFILLED = "SUBMISSIONS_LIST_FULFILLED";
export const SUBMISSIONS_LIST_REJECTED = "SUBMISSIONS_LIST_REJECTED";
