export const GET_SUBMISSION_LIST_FULFILLED = "GET_SUBMISSION_LIST_FULFILLED";
export const GET_SUBMISSION_LIST_REJECTED = "GET_SUBMISSION_LIST_REJECTED";

export const FETCH_SUBMISSION_FULFILLED = "FETCH_SUBMISSION_FULFILLED";
export const FETCH_SUBMISSION_REJECTED = "FETCH_SUBMISSION_REJECTED";


export const PUBLISH_SUBMISSION_FULFILLED = "PUBLISH_SUBMISSION_FULFILLED";
export const PUBLISH_SUBMISSION_REJECTED = "PUBLISH_SUBMISSION_REJECTED";
