version: "3"
services:
  elasticsearch:
    build: ./
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - nginx-proxy
networks:
  nginx-proxy:
